server:
  port: 8081
  servlet:
    context-path: /sh
logging:
  config: classpath:logback.xml

com:
  sh:
    datasource:
      url: jdbc:mysql://39.98.148.135:3306/hapiactivite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
      dbType: mysql
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize: 8
      minIdle: 8
      maxActive: 16
      entityPackageToScan: com.sh.*.entity
      hibernateDialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernateHbm2ddlAuto: none
      showSql: true

# 上传路径
upload:
  address: C://MyWorkSpace//Tomcat//apache-tomcat-8.0.45//webapps//qiche//

# 外放访问路径
show:
  address: http://39.98.148.135/

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB


